# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Scale app and run migrations
        run: |
          echo "Scaling app and running migrations..."
          flyctl scale count 1
          echo "Waiting for app to be ready..."
          sleep 30  # Give the app some time to start up
          echo "Running migrations..."
          flyctl ssh console -C "/app/bin/migrate"
          echo "Migrations completed."
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}